app = 'vitrine-backend--0mx-a'
primary_region = 'gru'

[build]

[deploy]
  release_command = '/bin/sh /var/www/html/docker/release.sh'

[env]
  APP_ENV        = 'production'
  APP_DEBUG      = 'false'
  LOG_CHANNEL    = 'stderr'
  LOG_LEVEL      = 'warning'
  COOKIE_DOMAIN  = '.pauloricardo.dev.br'
  REDIS_CLIENT   = 'predis'
  CACHE_STORE    = 'redis'
  R2_BUCKET      = 'vitrine'
  R2_PUBLIC_URL  = 'https://media.pauloricardo.dev.br'
  FILESYSTEM_DISK = 'r2'

[http_service]
  internal_port       = 8080
  force_https         = true
  auto_stop_machines  = 'stop'
  auto_start_machines = true
  min_machines_running = 0

  [http_service.concurrency]
    type       = 'requests'
    soft_limit = 200
    hard_limit = 250

[[vm]]
  memory   = '512mb'
  cpu_kind = 'shared'
  cpus     = 1

[[statics]]
  guest_path = '/var/www/html/public'
  url_prefix = '/build'
